### ISSUE TITLE
How to communicate among coroutines?

### ISSUE THREAD

**Issue by GReagle** [keplerproject/copas#34]
Can the handlers communicate via channels as in libmill (http://libmill.org/tutorial.html#step6) or Haskell (http://hackage.haskell.org/package/base-4.8.1.0/docs/Control-Concurrent-Chan.html)?

If not, how should they avoid race conditions?

**Comment by GReagle** [comment]
Here is a code sample to illustrate.  Do I need to lock or otherwise protect the variables succeeded and started since I am modifying them from multiple threads?
```require('strict')
local socket = require "socket"
local copas = require 'copas'

local succeeded, started = 0, 0
local quit = false

function dialog(skt)
    local line
    started = started + 1
    copas.send(skt, 'What is your name?\n')
    line = copas.receive(skt, '*l')
    if line then
        if line=='q' then
            quit=true
            copas.send(skt, 'Goodbye!\n')
        else
            copas.send(skt, 'Hello '..line..'\n')
        end
        succeeded = succeeded + 1
    end
end

local port = arg[1] and tonumber(arg[1]) or 5555
local server = assert(socket.bind("*", port))
copas.addserver(server, dialog)
repeat
    copas.step()
    print('succeded: '..succeeded..';  started: '..started)
until quit
print('succeded: '..succeeded..';  started: '..started)
```

**Comment by Tieske** [comment]
Lua is single threaded, and does not use pre-emptive multitasking. Hence the Lua code Always runs on its own, never simultaneously. So simple structures are always safe, just complex structures with multiple modifications in one critical section require some attention.

As long as you keep/complete your critical code in between 2 socket function calls (which implicitly yield control) you're good to go. Only when you relinguish control to the Copas scheduler other code might run and modify some data structures.

Obviously a function like `sleep` will directly yield control. But the socket functions like `receive` and `send` will do so as well, but there it is less obvious. Especially if you wrap the socket, then it just looks like a blocking luasocket call which it really isn't anymore.

If you need a lock; use a simple Lua datastructure, it's cooperative Multi-tasking, so any simple Lua value can only ever be modified by one piece of Lua code at a time.

In your case you do not need a lock, as your data structures will always be consistent because you use simple Lua values.

A lock requiring example might be; yielding while sorting a large table. A table with addresses is designed to be sorted always. Now when inserting a new address, a sorting operation must follow to make sure the list remains properly sorted. If you halfway sorting the table yield control, the table is not in a consistent state. Any other code that now runs (while the sorting is yielded) will expect the table to be sorted, though it might not be.
In this case you would set a flag `tableSorted` to `false` when starting to sort, and set it back to `true` when completing the sort.
Any code accessing the table would first check `tableSorted` before accessing it.

You need to be aware of the implicit yields, but in practice the possibilities for race conditions are far less than with pre-emptive multitasking.

hope this helps. If your question is answered, then please close the issue, or if not answered, let me know...

**Comment by GReagle** [comment]
Great explanation.  Thanks!
