### ISSUE TITLE
Rockspec depends on non-existing luasocket 2.1

### ISSUE THREAD

**Issue by stepelu** [keplerproject/copas#45]
As in https://github.com/keplerproject/xavante/issues/19, would it please be possible to update the `luasocket` dependency to `3.0rc1` ?

**Comment by Tieske** [comment]
Iirc this was done to enforce using 3.0 version, anticipating a stable release. And effectively it will select the mentioned version.

**Comment by stepelu** [comment]
Yes it does, my issue is that usually major releases are used to signal API breakage.

While luarocks does not, my distribution (which import rocks) relies on semantic versioning, according to which a module versioned 3.0 is incompatible with one versioned 2.1.

Using version 3.0rc1 would in  my opinion make the requirements clearer and help with my use case.

**Comment by hishamhm** [comment]
@stepelu Neither Copas, Xavante or LuaSocket use SemVer. Your approach of relying on it for packages that don't use it is fundamentally broken, sorry. At the risk of sounding even more blunt: projects won't start changing the way they version just to help your project.

And also, you are misinterpreting SemVer: releasing a (X+1).Y.Z means that it includes incompatible APIs from X.Y.Z, but that doesn't mean that a project A that depends on X.Y.Z of project B won't work with B version (X+1).Y.Z, because it may use only the subset of the APIs that haven't changed. By conservatively locking dependencies to an older version, you are making your users a disservice, as even if the APIs are functionally compatible (so staying in the older version "wouldn't hurt"), you are denying them any other non-functional benefits of a newer version, such as performance improvements. Also, a developer of B (X+1).Y.Z won't maintain the older X series forever, so in the future things such as security fixes may not be backported to older versions that your overly-conservative dependency system is clinging to.

**Comment by hishamhm** [comment]
I suggest closing this one as it is effectively, not a bug.

**Comment by stepelu** [comment]
In the same way Luarocks approach of not using any versioning scheme (unless 'bigger is better' can be considered one) is fundamentally broken too.
If the new 2.0 release of Copas would have been incompatible with the 1.Y branch, all users of Xavante would have got a broken installation from the day the the new Copas was released onward, clearly not an ideal situation and not a policy I am going to adopt.

I am not doing my users a disservice: I am striking a tradeoff between easiness of updates and robustness of the installed system at the major version point. 
Even if semantic versioning is not used in luarocks, in for most people a new major release means 'all bets are off', hence it represents a more risky transaction.

Anyway, I patched the rockspec manually (sigh) on my side so feel free to close this issue.

I raised the issue here as the proposed change would make both luarocks and my distribution happy. 
Moreover it makes it clearer (to the human viewer?) what the intended dependency is.

**Comment by Tieske** [comment]
> I raised the issue here as the proposed change would make both luarocks and my distribution happy. 
Moreover it makes it clearer (to the human viewer?) what the intended dependency is.

I'll update it after the final release of LuaSocket 3.0. Closing this for now.
